### ISSUE TITLE
Predict 2014 Result

### ISSUE THREAD

**Issue by azzouzze** [neaorin/PredictTheWorldCup#2]
folks, 

I was interested to see how well does this prediction model works. so wanted to make a jump back in time and see if it would predict the 2014 world cup result.
Can someone who has the code working try it and post the result ?

thank you

**Comment by neaorin** [comment]
I don't have time to try this out, but you have to remember that the idea is NOT to predict a single winner, but instead a distribution of possible match results, and then use that in multiple (10,000 or more) simulations in order to predict a distribution of tournament winners.

So even if Germany would be considered the main favorite to win by the model, they would still be winning the tournament in only maybe 12 - 15 percent of the total simulated runs. 
It's just a reflection of the variance which exists in World Cup football.

If you or anyone else would like to try this for the 2014 WC, here are the steps:

1. Update the [WC draw file](https://github.com/neaorin/PredictTheWorldCup/blob/master/src/TournamentSim/wc2018qualified.csv) with the 2014 qualified teams and draw.
2. Update the [WC schedule file](https://github.com/neaorin/PredictTheWorldCup/blob/master/src/TournamentSim/wc2018schedule.csv) with the 2014 tournament schedule.
3. Update the [WC tournament simulator](https://github.com/neaorin/PredictTheWorldCup/blob/master/src/TournamentSim/simulateworldcup.py) with the 2014 tournament rules - I believe there were some different tie-breaking rules for the group stage than in 2018.
4. Drop all the matches played before the 2014 tournament from the dataset.
5. Re-run the data preparation, model training, generate predictions and tournament simulator.

I'm closing this issue now.
Thanks
